DROP SEQUENCE MYBOARDSQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYBOARDSQ;

--번호, 작성자, 제목, 내용, 작성일자
CREATE TABLE MYBOARD(
SEQ NUMBER PRIMARY KEY,
WRITER VARCHAR2(50) NOT NULL,
TITLE VARCHAR2(2000) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
REGDATE DATE NOT NULL
);

SELECT * FROM MYBOARD;

INSERT INTO MYBOARD VALUES(MYBOARDSQ.NEXTVAL,'관리자','테스트제목','테스트중입니다.','17/10/25');